//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMLAPI.CargoWisePaymentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cargowise.com/Accounting/", ConfigurationName="CargoWisePaymentService.UpdateInvoicePaymentDetailsServiceSoap")]
    public interface UpdateInvoicePaymentDetailsServiceSoap {
        
        // CODEGEN: Generating message contract since message UpdateInvoicePaymentDetailsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://cargowise.com/Accounting/UpdateInvoicePaymentDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResponseBase))]
        XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsResponse1 UpdateInvoicePaymentDetails(XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cargowise.com/Accounting/UpdateInvoicePaymentDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsResponse1> UpdateInvoicePaymentDetailsAsync(XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cargowise.com/Accounting/")]
    public partial class SecuritySOAPHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpdateInvoicePaymentDetailsResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cargowise.com/Accounting/")]
    public partial class ResponseBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool succeededField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Succeeded {
            get {
                return this.succeededField;
            }
            set {
                this.succeededField = value;
                this.RaisePropertyChanged("Succeeded");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cargowise.com/Accounting/")]
    public partial class UpdateInvoicePaymentDetailsResponse : ResponseBase {
        
        private UpdateInvoicePaymentDetailsRequest originalRequestField;
        
        private string currencyCodeField;
        
        private decimal invoiceTotalField;
        
        private decimal paidAmountField;
        
        private string paymentStatusField;
        
        private System.DateTime fullyPaidDateField;
        
        private bool fullyPaidDateHasValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public UpdateInvoicePaymentDetailsRequest OriginalRequest {
            get {
                return this.originalRequestField;
            }
            set {
                this.originalRequestField = value;
                this.RaisePropertyChanged("OriginalRequest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CurrencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
                this.RaisePropertyChanged("CurrencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal InvoiceTotal {
            get {
                return this.invoiceTotalField;
            }
            set {
                this.invoiceTotalField = value;
                this.RaisePropertyChanged("InvoiceTotal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal PaidAmount {
            get {
                return this.paidAmountField;
            }
            set {
                this.paidAmountField = value;
                this.RaisePropertyChanged("PaidAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PaymentStatus {
            get {
                return this.paymentStatusField;
            }
            set {
                this.paymentStatusField = value;
                this.RaisePropertyChanged("PaymentStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime FullyPaidDate {
            get {
                return this.fullyPaidDateField;
            }
            set {
                this.fullyPaidDateField = value;
                this.RaisePropertyChanged("FullyPaidDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool FullyPaidDateHasValue {
            get {
                return this.fullyPaidDateHasValueField;
            }
            set {
                this.fullyPaidDateHasValueField = value;
                this.RaisePropertyChanged("FullyPaidDateHasValue");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cargowise.com/Accounting/")]
    public partial class UpdateInvoicePaymentDetailsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accLedgerField;
        
        private string transactionTypeField;
        
        private string transactionNumberField;
        
        private string jobTransactionNumberField;
        
        private string internalReferenceField;
        
        private string paymentReferenceField;
        
        private string companyCodeField;
        
        private string orgCodeField;
        
        private System.Nullable<System.DateTime> paymentDateField;
        
        private decimal amountPaidInCompanyCurrencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccLedger {
            get {
                return this.accLedgerField;
            }
            set {
                this.accLedgerField = value;
                this.RaisePropertyChanged("AccLedger");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TransactionType {
            get {
                return this.transactionTypeField;
            }
            set {
                this.transactionTypeField = value;
                this.RaisePropertyChanged("TransactionType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TransactionNumber {
            get {
                return this.transactionNumberField;
            }
            set {
                this.transactionNumberField = value;
                this.RaisePropertyChanged("TransactionNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string JobTransactionNumber {
            get {
                return this.jobTransactionNumberField;
            }
            set {
                this.jobTransactionNumberField = value;
                this.RaisePropertyChanged("JobTransactionNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string InternalReference {
            get {
                return this.internalReferenceField;
            }
            set {
                this.internalReferenceField = value;
                this.RaisePropertyChanged("InternalReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PaymentReference {
            get {
                return this.paymentReferenceField;
            }
            set {
                this.paymentReferenceField = value;
                this.RaisePropertyChanged("PaymentReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CompanyCode {
            get {
                return this.companyCodeField;
            }
            set {
                this.companyCodeField = value;
                this.RaisePropertyChanged("CompanyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string OrgCode {
            get {
                return this.orgCodeField;
            }
            set {
                this.orgCodeField = value;
                this.RaisePropertyChanged("OrgCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<System.DateTime> PaymentDate {
            get {
                return this.paymentDateField;
            }
            set {
                this.paymentDateField = value;
                this.RaisePropertyChanged("PaymentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal AmountPaidInCompanyCurrency {
            get {
                return this.amountPaidInCompanyCurrencyField;
            }
            set {
                this.amountPaidInCompanyCurrencyField = value;
                this.RaisePropertyChanged("AmountPaidInCompanyCurrency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateInvoicePaymentDetails", WrapperNamespace="http://cargowise.com/Accounting/", IsWrapped=true)]
    public partial class UpdateInvoicePaymentDetailsRequest1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://cargowise.com/Accounting/")]
        public XMLAPI.CargoWisePaymentService.SecuritySOAPHeader SecuritySOAPHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cargowise.com/Accounting/", Order=0)]
        public XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsRequest request;
        
        public UpdateInvoicePaymentDetailsRequest1() {
        }
        
        public UpdateInvoicePaymentDetailsRequest1(XMLAPI.CargoWisePaymentService.SecuritySOAPHeader SecuritySOAPHeader, XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsRequest request) {
            this.SecuritySOAPHeader = SecuritySOAPHeader;
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateInvoicePaymentDetailsResponse", WrapperNamespace="http://cargowise.com/Accounting/", IsWrapped=true)]
    public partial class UpdateInvoicePaymentDetailsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cargowise.com/Accounting/", Order=0)]
        public XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsResponse UpdateInvoicePaymentDetailsResult;
        
        public UpdateInvoicePaymentDetailsResponse1() {
        }
        
        public UpdateInvoicePaymentDetailsResponse1(XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsResponse UpdateInvoicePaymentDetailsResult) {
            this.UpdateInvoicePaymentDetailsResult = UpdateInvoicePaymentDetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UpdateInvoicePaymentDetailsServiceSoapChannel : XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateInvoicePaymentDetailsServiceSoapClient : System.ServiceModel.ClientBase<XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsServiceSoap>, XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsServiceSoap {
        
        public UpdateInvoicePaymentDetailsServiceSoapClient() {
        }
        
        public UpdateInvoicePaymentDetailsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UpdateInvoicePaymentDetailsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateInvoicePaymentDetailsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateInvoicePaymentDetailsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsResponse1 XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsServiceSoap.UpdateInvoicePaymentDetails(XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsRequest1 request) {
            return base.Channel.UpdateInvoicePaymentDetails(request);
        }
        
        public XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsResponse UpdateInvoicePaymentDetails(XMLAPI.CargoWisePaymentService.SecuritySOAPHeader SecuritySOAPHeader, XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsRequest request) {
            XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsRequest1 inValue = new XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsRequest1();
            inValue.SecuritySOAPHeader = SecuritySOAPHeader;
            inValue.request = request;
            XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsResponse1 retVal = ((XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsServiceSoap)(this)).UpdateInvoicePaymentDetails(inValue);
            return retVal.UpdateInvoicePaymentDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsResponse1> XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsServiceSoap.UpdateInvoicePaymentDetailsAsync(XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsRequest1 request) {
            return base.Channel.UpdateInvoicePaymentDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsResponse1> UpdateInvoicePaymentDetailsAsync(XMLAPI.CargoWisePaymentService.SecuritySOAPHeader SecuritySOAPHeader, XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsRequest request) {
            XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsRequest1 inValue = new XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsRequest1();
            inValue.SecuritySOAPHeader = SecuritySOAPHeader;
            inValue.request = request;
            return ((XMLAPI.CargoWisePaymentService.UpdateInvoicePaymentDetailsServiceSoap)(this)).UpdateInvoicePaymentDetailsAsync(inValue);
        }
    }
}
